#!/usr/bin/env python3
"""PRACTICE site test: the pages are served from the repo files but under the REAL public origin
(https://cmheating.github.io/sales-tools/ — mapped by Playwright, no network), so the hostname check, practice flag and
in-browser API (js/practice-api.js) behave exactly as they will for a tester. Exits non-zero on any failure."""
import json, mimetypes, os, sys, datetime
from playwright.sync_api import sync_playwright
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
ORIGIN = 'https://cmheating.github.io/sales-tools/'; FAILS = []; EXTERNAL = []
d = lambda n: (datetime.date.today() + datetime.timedelta(days=n)).isoformat()

def ok(label, cond):
    print(('PASS ' if cond else 'FAIL ') + label)
    if not cond: FAILS.append(label)

def handler(route):
    url = route.request.url
    if url.startswith(ORIGIN):
        rel = url[len(ORIGIN):].split('#')[0].split('?')[0] or 'index.html'
        path = os.path.join(ROOT, rel)
        if os.path.isdir(path): path = os.path.join(path, 'index.html')
        if os.path.exists(path):
            return route.fulfill(body=open(path, 'rb').read(), content_type=mimetypes.guess_type(path)[0] or 'text/plain')
        return route.fulfill(status=404, body='not found')
    if 'fonts.googleapis.com' in url or 'fonts.gstatic.com' in url: return route.abort()
    EXTERNAL.append(url); return route.abort()


URL = ORIGIN + 'install-requirements.html#job=900001&cust=Sample+Alpha&date=%s&rep=Samir+Khoury&practice=1' % d(5)
with sync_playwright() as p:
    b = p.chromium.launch(headless=True); ctx = b.new_context(viewport={'width': 390, 'height': 844})
    ctx.route('**/*', handler); pg = ctx.new_page(); errs = []; pg.on('pageerror', lambda e: errs.append(str(e)))
    api = lambda method, path, body=None: pg.evaluate("""async ([m,p,b]) => { const r = await fetch(p, {method:m, headers:{'Content-Type':'application/json'}, body: JSON.stringify(b)}); return [r.status, await r.json()]; }""", [method, path, body])
    pg.goto(ORIGIN + 'practice/index.html'); pg.wait_for_timeout(500); api('POST', '/api/reset', {})
    pg.goto(URL); pg.reload(); pg.wait_for_timeout(900)
    # F4: partial (6 of 7, Heat load / AHRI unanswered) -- messages must agree
    pg.select_option('#pay', index=1)
    for i in ['stock', 'mat', 'video', 'photos', 'i-labor']: pg.click(f'button[data-id="{i}"][data-v="yes"]')
    pg.click('button[data-id="rebate"][data-v="na"]')
    pg.wait_for_timeout(300)
    ok('F4 partial: Submit enabled (Heat load/AHRI stay optional)', not pg.is_disabled('#submitBtn'))
    ok('F4 partial: banner is not "Needs you" when only optional items are open', 'Needs you' not in pg.inner_text('#needs') and 'Optional' in pg.inner_text('#needs'))
    ok('F4 partial: footer says ready + optional count', 'Ready to submit' in pg.inner_text('#barTxt') and 'optional open' in pg.inner_text('#barTxt'))
    pg.click('#submitBtn'); pg.wait_for_timeout(600)
    ok('F4 submitted: header, banner, footer agree', 'Submitted' in pg.inner_text('#barTxt') and 'Submitted' in pg.inner_text('#needs') and pg.inner_text('#submitBtn') == 'Back to my projects' and not pg.is_visible('#parkBtn'))
    api('POST', '/api/reopen', {'job': '900001', 'by': 'Amy', 'reason': 'Photos missing'}); pg.reload(); pg.wait_for_timeout(900)
    ok('F4 reopened: not "Submitted"; Submit enabled again and footer says so', 'Submitted' not in pg.inner_text('#barTxt') and not pg.is_disabled('#submitBtn') and 'Sent back by Amy' in pg.inner_text('#needs'))
    # F3: Save & exit closes after success, keeps data, no duplicate
    pg.click('#parkBtn'); pg.select_option('#parkReason', index=1); pg.fill('#parkDate', d(3)); pg.dblclick('#parkSave'); pg.wait_for_timeout(700)
    ok('F3 Save & exit closes the modal after success', not pg.locator('#parkModal.on').count())
    ok('F3 footer confirms parked, answers kept', 'Parked' in pg.inner_text('#barTxt') and pg.inner_text('#ringN').startswith('6'))
    c, r = api('GET', '/api/record?job=900001'); ok('F3 parked stored once on the record', r['record'].get('parked') is not None)
    pg.wait_for_timeout(900); ok('F3 Save & exit goes back to the project list (not stuck on the form)', 'practice/index.html' in pg.url)
    pg.goto(URL); pg.reload(); pg.wait_for_timeout(800)
    # F2: landscape modal inside the viewport
    pg.set_viewport_size({'width': 844, 'height': 390}); pg.click('#parkBtn'); pg.wait_for_timeout(300)
    box = pg.evaluate("(()=>{const h=document.getElementById('parkH').getBoundingClientRect(),s=document.getElementById('parkSave').getBoundingClientRect(),sh=document.querySelector('.sheet').getBoundingClientRect();return {h:h.top,s:s.bottom,sh:sh.height,vh:innerHeight}})()")
    ok('F2 landscape: sheet fits viewport, Save reachable (%s)' % box, box['sh'] <= box['vh'] + 1 and box['s'] <= box['vh'] + 1)
    pg.evaluate("document.querySelector('.sheet').scrollTop=0"); ok('F2 landscape: heading visible at top', pg.evaluate("document.getElementById('parkH').getBoundingClientRect().top") >= 0)
    pg.keyboard.press('Escape')
    # F1: narrow footer
    for w, h in [(320, 670), (390, 844)]:
        pg.set_viewport_size({'width': w, 'height': h}); pg.wait_for_timeout(200)
        r = pg.evaluate("(()=>{const b=document.querySelector('.bar').getBoundingClientRect();return {bh:b.height,vh:innerHeight,sw:document.getElementById('submitBtn').getBoundingClientRect().width,pw:document.getElementById('parkBtn').getBoundingClientRect().width}})()")
        ok('F1 footer at %dx%d is <=25%% of viewport and both buttons usable (%s)' % (w, h, r), r['bh'] <= r['vh'] * 0.25 and r['sw'] >= 100 and r['pw'] >= 100)
    pg.set_viewport_size({'width': 768, 'height': 1024}); pg.wait_for_timeout(200)
    ok('tablet: no horizontal overflow', pg.evaluate("document.documentElement.scrollWidth<=innerWidth"))
    # decisions 2026-10-04: rental sticky, warn on incomplete Not done, review lockout banner
    api('POST', '/api/reset', {}); pg.set_viewport_size({'width': 390, 'height': 844}); pg.goto(URL); pg.reload(); pg.wait_for_timeout(800)
    pg.select_option('#pay', label=[o for o in pg.eval_on_selector_all('#pay option', 'els=>els.map(e=>e.textContent)') if 'ental' in o][0]); pg.click('button[data-id="r-contract"][data-v="yes"]')
    pg.select_option('#pay', label=[o for o in pg.eval_on_selector_all('#pay option', 'els=>els.map(e=>e.textContent)') if 'Paid in full' in o][0]); pg.wait_for_timeout(300)
    ok('rental paperwork stays on the list once answered, even if payment changes', pg.is_visible('#sec-rental'))
    pg.click('button[data-id="stock"][data-v="no"]'); dlg = []; pg.once('dialog', lambda x: (dlg.append(x.message), x.dismiss()))
    pg.click('.topbar .back'); pg.wait_for_timeout(300); ok('leaving with a Not done lacking why/date warns (and Cancel stays)', dlg and 'Not done' in dlg[0] and 'install-requirements' in pg.url)
    pg.click('button[data-id="stock"][data-v="yes"]')
    for i in ['mat', 'video', 'photos', 'i-labor']: pg.click(f'button[data-id="{i}"][data-v="yes"]')
    pg.click('button[data-id="rebate"][data-v="na"]')
    for i in ['r-contract', 'r-penny', 'r-credit', 'r-payauth', 'r-dl', 'r-deed']: pg.click(f'button[data-id="{i}"][data-v="yes"]')
    pg.click('#submitBtn'); pg.wait_for_timeout(500)
    api('POST', '/api/lane', {'job': '900001', 'by': 'Lyle', 'lane': 'install', 'items': {'mat-ok': {'result': 'verified'}}}); pg.reload(); pg.wait_for_timeout(800)
    ok('in review: banner names the manager, inputs locked', 'Under review' in pg.inner_text('#needs') and 'Lyle' in pg.inner_text('#needs') and pg.locator('.seg button').first.is_disabled())
    # past dates rejected; locked 6-of-8 job never says "you can still submit"; manager chip stays orange until verified
    api('POST', '/api/reset', {}); pg.goto(URL); pg.reload(); pg.wait_for_timeout(800)
    pg.select_option('#pay', index=1)
    for i in ['stock', 'mat', 'video', 'photos', 'i-labor']: pg.click(f'button[data-id="{i}"][data-v="yes"]')
    pg.click('button[data-id="rebate"][data-v="na"]')
    pg.click('#submitBtn'); pg.wait_for_timeout(500)
    api('POST', '/api/lane', {'job': '900001', 'by': 'Lyle', 'lane': 'install', 'signoff': 'confirmed', 'items': {}}); pg.reload(); pg.wait_for_timeout(800)
    ok('locked 6-of-8: banner says under review, never "submit now"', 'Under review' in pg.inner_text('#needs') and 'submit now' not in pg.inner_text('#needs'))
    mp = ctx.new_page(); mp.goto(ORIGIN + 'install-qc.html?practice=1&as=Lyle'); mp.wait_for_timeout(900)
    cls = mp.evaluate("[...document.querySelectorAll('#rows .lane')].map(e=>e.className+'|'+e.textContent)")
    ok('manager chip: confirmed with 0 items verified is orange (mid), no check (%s)' % cls[:3], any('mid' in c and '✓' not in c for c in cls) and not any(('ok' in c.split('|')[0].split()) for c in cls))
    api('POST', '/api/reset', {}); pg.goto(URL); pg.reload(); pg.wait_for_timeout(800); pg.click('button[data-id="stock"][data-v="no"]')
    pg.select_option('#why-stock select', index=1); pg.evaluate("document.querySelector('#why-stock input[type=date]').value='2020-01-01';document.querySelector('#why-stock input[type=date]').dispatchEvent(new Event('change'))"); pg.wait_for_timeout(200)
    ok('a past "by when" date is cleared (Submit stays blocked)', pg.input_value('#why-stock input[type=date]') == '' and pg.is_disabled('#submitBtn'))
    pg.click('#parkBtn'); pg.select_option('#parkReason', index=1); pg.fill('#parkDate', '2020-01-01'); pg.click('#parkSave'); pg.wait_for_timeout(300)
    ok('past wrap-up date refused, modal stays open', 'passed' in pg.inner_text('#parkMsg') and pg.locator('#parkModal.on').count() == 1)
    ok('park date is labelled Pacific time', 'pacific' in pg.inner_text('#parkModal').lower())
    # retest #6: send back -> HCA corrects and resubmits -> reload shows matching Submitted state
    api('POST', '/api/reset', {}); pg.goto(URL); pg.reload(); pg.wait_for_timeout(800)
    pg.select_option('#pay', index=1)
    for i in ['stock', 'mat', 'video', 'photos', 'i-labor']: pg.click(f'button[data-id="{i}"][data-v="yes"]')
    pg.click('button[data-id="rebate"][data-v="na"]')
    pg.click('#submitBtn'); pg.wait_for_timeout(500)
    api('POST', '/api/reopen', {'job': '900001', 'by': 'Amy', 'reason': 'Stock needs confirming'}); pg.reload(); pg.wait_for_timeout(800)
    ok('sent back: note shown, Submit enabled', 'Stock needs confirming' in pg.inner_text('#needs') and not pg.is_disabled('#submitBtn'))
    pg.click('#submitBtn'); pg.wait_for_timeout(600); pg.reload(); pg.wait_for_timeout(800)
    ok('after resubmit + reload: note cleared, banner/footer say Submitted, Submit disabled', 'Stock needs' not in pg.inner_text('#needs') and 'Submitted' in pg.inner_text('#needs') and 'Submitted' in pg.inner_text('#barTxt') and 'Ready to submit' not in pg.inner_text('#barTxt') and pg.inner_text('#submitBtn') == 'Back to my projects' and not pg.is_visible('#parkBtn'))
    # verifier counterexample: rental picked by mistake must be removable (N/A) and not block Submit
    api('POST', '/api/reset', {}); pg.goto(URL); pg.reload(); pg.wait_for_timeout(800)
    pg.select_option('#pay', label=[o for o in pg.eval_on_selector_all('#pay option', 'els=>els.map(e=>e.textContent)') if 'ental' in o][0]); pg.click('button[data-id="r-contract"][data-v="yes"]')
    pg.select_option('#pay', label=[o for o in pg.eval_on_selector_all('#pay option', 'els=>els.map(e=>e.textContent)') if 'Paid in full' in o][0])
    for i in ['stock', 'mat', 'video', 'photos', 'i-labor']: pg.click(f'button[data-id="{i}"][data-v="yes"]')
    pg.click('button[data-id="rebate"][data-v="na"]')
    ok('mistaken rental: rental rows offer N/A', pg.locator('button[data-id="r-penny"][data-v="na"]').count() == 1)
    pg.click('button[data-id="r-contract"][data-v="na"]')
    pg.wait_for_timeout(300); ok('mistaken rental: N/A on the one answered item drops the rental section and Submit works', not pg.is_visible('#sec-rental') and not pg.is_disabled('#submitBtn'))
    # tab-close warning
    api('POST', '/api/reset', {}); pg.goto(URL); pg.reload(); pg.wait_for_timeout(700)
    ok('page tells HCAs that closing does not save with the office', 'does not save your work' in pg.inner_text('#leaveHint'))
    p3 = ctx.new_page(); p3.goto(URL); p3.reload(); p3.wait_for_timeout(700); kinds = []; p3.on('dialog', lambda x: (kinds.append(x.type), x.dismiss()))
    p3.close(run_before_unload=True); pg.wait_for_timeout(300); ok('empty form: closing the tab does not warn', not kinds)
    p4 = ctx.new_page(); p4.goto(URL); p4.reload(); p4.wait_for_timeout(700); kinds2 = []; p4.on('dialog', lambda x: (kinds2.append(x.type), x.accept()))
    p4.select_option('#pay', index=1); p4.click('button[data-id="stock"][data-v="yes"]'); p4.close(run_before_unload=True); pg.wait_for_timeout(400)
    ok('answers entered, not submitted: closing the tab warns', 'beforeunload' in kinds2)
    # submit takes the HCA back to the project list (no stray Save & exit on a finished project)
    api('POST', '/api/reset', {}); pg.goto(URL); pg.reload(); pg.wait_for_timeout(700); pg.select_option('#pay', index=1)
    for i in ['stock', 'mat', 'video', 'photos', 'i-labor']: pg.click(f'button[data-id="{i}"][data-v="yes"]')
    pg.click('button[data-id="rebate"][data-v="na"]')
    pg.click('#submitBtn'); pg.wait_for_timeout(700)
    ok('after Submit: Save & exit is gone and the button says Back to my projects', not pg.is_visible('#parkBtn') and pg.inner_text('#submitBtn') == 'Back to my projects')
    ok('after Submit the email-to-Install draft appears instead of leaving the page', pg.is_visible('#sentModal'))
    pg.click('#sentBack'); pg.wait_for_timeout(800); ok('Back to my projects returns to the project list', 'practice/index.html' in pg.url)
    pg.goto(URL); pg.reload(); pg.wait_for_timeout(800); ok('reopening a submitted project also offers Back to my projects (no Save & exit)', not pg.is_visible('#parkBtn') and pg.inner_text('#submitBtn') == 'Back to my projects')
    # N/A rules (owner, 2026-10-04/05): Permit/jurisdiction and Heat load are never N/A; AHRI keeps N/A (not a full system)
    api('POST', '/api/reset', {}); pg.goto(URL); pg.reload(); pg.wait_for_timeout(700)
    na = lambda i: pg.locator(f'button[data-id="{i}"][data-v="na"]').count()
    ok('Permit and Heat load have no N/A; AHRI keeps it', na('permit') == 0 and na('heatload') == 0 and na('ahri') == 1)
    # simplified answers (owner, 2026-10-05): materials / photos / video = Yes or Working on it; install labor = Yes or No; no Electrical card
    api('POST', '/api/reset', {}); pg.goto(URL); pg.reload(); pg.wait_for_timeout(700)
    lab = lambda i: pg.eval_on_selector_all(f'button[data-id="{i}"]', 'els => els.map(e => e.textContent.trim())')
    ok('Materials list, Layout photos and Walkthrough video are Yes / Working on it', lab('mat') == ['Yes', 'Working on it'] and lab('photos') == ['Yes', 'Working on it'] and lab('video') == ['Yes', 'Working on it'])
    ok('Install labor billed correctly? is Yes / No', lab('i-labor') == ['Yes', 'No'])
    ok('there is no Electrical card (disconnect, service outlet and electrical labor are gone)', pg.locator('#sec-elec').count() == 0 and pg.locator('button[data-id="e-labor"]').count() == 0 and pg.locator('button[data-id="e-outlet"]').count() == 0 and pg.locator('button[data-id="e-disconnect"]').count() == 0)
    ok('there is no Heads-up for Install card; Filter size sits under Vendor in the equipment section', pg.locator('#sec-email').count() == 0 and pg.is_visible('#row-stock #filterTxt') and pg.is_visible('#row-stock #vendorTxt'))
    pg.select_option('#pay', index=1)
    for i in ['stock', 'mat', 'video', 'photos']: pg.click(f'button[data-id="{i}"][data-v="yes"]')
    pg.click('button[data-id="rebate"][data-v="na"]'); pg.wait_for_timeout(200)
    ok('Submit stays blocked until install labor is answered', pg.is_disabled('#submitBtn') and 'labor' in pg.inner_text('#barTxt').lower())
    pg.click('button[data-id="i-labor"][data-v="yes"]'); pg.wait_for_timeout(200); ok('install labor answered => Submit enabled', not pg.is_disabled('#submitBtn'))
    pg.click('button[data-id="mat"][data-v="work"]'); pg.wait_for_timeout(200); ok('Working on it still counts as answered (Submit stays enabled)', not pg.is_disabled('#submitBtn'))
    # Codex review (PR #51): an N/A saved before the button was removed must not count as an answer
    api('POST', '/api/reset', {}); pg.goto(URL)
    pg.evaluate("() => { const d = JSON.parse(localStorage.getItem('cmh_practice_db_v1')); d.records['900001'] = {hca: {pay: '\\u2714 Paid in full', items: {heatload: {v: 'na'}, permit: {v: 'na'}, stock: {v: 'yes'}}}}; localStorage.setItem('cmh_practice_db_v1', JSON.stringify(d)); }")
    pg.reload(); pg.wait_for_timeout(800)
    ok('stale N/A on Heat load / Permit is unanswered after load (rows show no selection, both still count in the total)', pg.locator('button[data-id="heatload"][aria-checked="true"]').count() == 0 and pg.locator('button[data-id="permit"][aria-checked="true"]').count() == 0 and pg.inner_text('#ringN').replace('\n', ' ') == '2 of 8')
    c, r = api('POST', '/api/hca', {'job': '900001', 'items': {'heatload': {'v': 'na'}}}); ok('API refuses N/A on Heat load', c == 400)
    c, r = api('POST', '/api/hca', {'job': '900001', 'items': {'permit': {'v': 'na'}}}); ok('API refuses N/A on Permit', c == 400)
    c, r = api('POST', '/api/hca', {'job': '900001', 'items': {'ahri': {'v': 'na'}}}); ok('API still accepts N/A on AHRI', c == 200)
    ok('no page errors', not errs); print(errs[:3]); b.close()
print('\n%d check(s) failed' % len(FAILS) if FAILS else '\nALL CHECKS PASSED'); sys.exit(1 if FAILS else 0)
